monroe:
  url: "http://enr.monroecounty.gov/"
suffolk:
  base_url: "http://apps.suffolkcountyny.gov/boe/eleres/{year}{election}"
chautauqua:
  base_url: "http://www.co.chautauqua.ny.us/departments/boe/Documents/20{year} {election}"
orange:
  url: "http://boe.co.orange.ny.us/"
